name: deploy-api-docs
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
     uses: vapor/api-docs/.github/workflows/build-and-deploy-docs-workflow.yml@075f25140e6975cb84add2046f96e922d184146c
     secrets: inherit
     with:
       package_name: vapor
       modules: Vapor,XCTVapor
