name: deploy-api-docs
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
     uses: vapor/api-docs/.github/workflows/build-and-deploy-docs-workflow.yml@001030401c9a0d0394a46bff286989281202d10f
     secrets: inherit
     with:
       package_name: vapor
       modules: Vapor,XCTVapor
